version: 2.1

orbs:
  node: circleci/node@4.7.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.15.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
workflows:
  version: 2
  build:
    jobs:
      - build